### PR TITLE
Widecoin: revise for Widecoin

### PR DESCRIPTION
**Pull request by widecoin-project**
Widecoin: revise for Widecoin

### CODE REVIEW

**Comment by widecoin-project** [comment]
www.widecoin.org

**Comment by 10gic** [comment]
I notice that widecoin is listed in https://github.com/satoshilabs/slips/blob/master/slip-0044.md.

In order to support new bitcoin fork more easily, I adjust some code recently. New forks can be supported just by changing https://github.com/10gic/btc-address-dump/blob/main/btc_address_dump/coins.yaml

```
wcn:
  src_code: https://github.com/widecoin-project/widecoin
  base58_prefix:
    pubkey: 73
    script: 33
    wif: 153
  bech32_hrp: wc
  hd_path:
    bip44: m/44'/613'/0'/0/0
    bip49: m/49'/613'/0'/0/0
    bip84: m/84'/613'/0'/0/0
wcn_test:
  src_code: https://github.com/widecoin-project/widecoin
  base58_prefix:
    pubkey: 111
    script: 65
    wif: 239
  bech32_hrp: tw
  hd_path:
    bip44: m/44'/1'/0'/0/0
    bip49: m/49'/1'/0'/0/0
    bip84: m/84'/1'/0'/0/0
```

@widecoin-project Could you help me to review above configuration? If these are correct, I will change it directly.

**Comment by widecoin-project** [comment]
should be ok.

**Comment by 10gic** [comment]
Support Widecoin in commit https://github.com/10gic/btc-address-dump/commit/281e368b04912c13b1a522f155d2bfc2e36b92a1

An example:
```
$ pip3 install -U btc-address-dump
$ btc_address_dump -c wcn 54a074ff9a62933a30ec96805731e79f46aeae1684253dfaa8d738bb27a10beb
private key (hex) = 54a074ff9a62933a30ec96805731e79f46aeae1684253dfaa8d738bb27a10beb
private key (WIF) = 694AfnHBCuYAVpvAcmLDCVtfcDjfA3kuuh6ZK5zE4CsGKVf9uBr
private key (WIF compressed) = PgYygArQ3YtYvEVfSrfnqkX3QTDHQwApXZyXcq1ad9NrcHnvDmuR
public key (uncompressed) = 044f41454a99121a2ab162450e1006667ea9fe83af2b61d82c0337c37b4ab718408600553df7c2535dac6ec6cfac0700df46bcd224c75acb72792411228923294a
public key (compressed) = 024f41454a99121a2ab162450e1006667ea9fe83af2b61d82c0337c37b4ab71840
hash160 of uncompressed public key = 373ab95d83dea60184a087702c90d6ce3f5c6f9f
hash160 of compressed public key = a9649ae720e3f73ef40c6607c180d25c36f3f917
legacy address (p2pkh uncompressed) = WTi4PhWNPT5hhvtRzufTnpRby2oo6Y5rpP
legacy address (p2pkh compressed) = We7hbWbtBQwmcC3ULThTkyt1uHzxMCzYw6
p2sh-segwit address (p2sh p2wpkh) = ENjxnSLa8x1z8hXYKrBVhs7yPJBTSMkHDk
bech32 address (p2wpkh) = wc1q49jf4eequ0mnaaqvvcrurqxjtsm087ghskqqj0
```

**Comment by widecoin-project** [comment]
how can verify WIF 694AfnHBCuYAVpvAcmLDCVtfcDjfA3kuuh6ZK5zE4CsGKVf9uBr  is correct ?

**Comment by 10gic** [comment]
> should be ok. please share me telegram ID i would ask something.

My telegram is here https://www.temporary-url.com/E0EC61

**Comment by 10gic** [comment]
> how can verify WIF 694AfnHBCuYAVpvAcmLDCVtfcDjfA3kuuh6ZK5zE4CsGKVf9uBr is correct ?

May be import it (bitcoin-cli importprivkey), then check the address.

**Comment by widecoin-project** [comment]
where you got this key 54a074ff9a62933a30ec96805731e79f46aeae1684253dfaa8d738bb27a10beb ?

**Comment by 10gic** [comment]
It's generated randomly. For example:
```
$ openssl rand -hex 32
f25e540e06f6a2e7d0e984b018ebc3dfcc4b3ad6bd63ce329b7a95b58a307e2e
```

**Comment by widecoin-project** [comment]
importprivkey "694AfnHBCuYAVpvAcmLDCVtfcDjfA3kuuh6ZK5zE4CsGKVf9uBr"

importprivkey(...)
null

why null ?

**Comment by 10gic** [comment]
Please check: https://en.bitcoin.it/wiki/How_to_import_private_keys#Import_Private_key.28s.29

**Comment by widecoin-project** [comment]
How to generate address base_58_key below ?

    "5KaBW9vNtWNhc3ZEDyNCiXLPdVPHCikRxSBWwV9NrpLLa4LsXi9",
    "e75d936d56377f432f404aabb406601f892fd49da90eb6ac558a733c93b47252",
    {
      "isCompressed": false,
	@@ -189,7 +189,7 @@
    }
  ],
  [
    "L1axzbSyynNYA8mCAhzxkipKkfHtAXYF4YQnhSKcLV8YXA874fgT",
    "8248bd0375f2f75d7e274ae544fb920f51784480866b102384190b1addfbaa5c",
    {
      "isCompressed": true,
	@@ -216,7 +216,7 @@
    }
  ],
  [
    "1Gqk4Tv79P91Cc1STQtU3s1W6277M2CVWu",
    "adc1cc2081a27206fae25792f28bbc55b831549d",
    {
      "addrType": "pubkey",
	@@ -225,7 +225,7 @@
    }
  ],
  [
    "33vt8ViH5jsr115AGkW6cEmEz9MpvJSwDk",
    "188f91a931947eddd7432d6e614387e32b244709",
    {
      "addrType": "script",
	@@ -243,7 +243,7 @@
    }
  ],
  [
    "2MxgPqX1iThW3oZVk9KoFcE5M4JpiETssVN",
    "3b9b3fd7a50d4f08d1a5b0f62f644fa7115ae2f3",
    {
      "addrType": "script",
	@@ -252,7 +252,7 @@
    }
  ],
  [
    "5HtH6GdcwCJA4ggWEL1B3jzBBUB8HPiBi9SBc5h9i4Wk4PSeApR",
    "091035445ef105fa1bb125eccfb1882f3fe69592265956ade751fd095033d8d0",
    {
      "isCompressed": false,
	@@ -261,7 +261,7 @@
    }
  ],
  [
    "L2xSYmMeVo3Zek3ZTsv9xUrXVAmrWxJ8Ua4cw8pkfbQhcEFhkXT8",
    "ab2b4bcdfc91d34dee0ae2a8c6b6668dadaeb3a88b9859743156f462325187af",
    {
      "isCompressed": true,
	@@ -288,7 +288,7 @@
    }
  ],
  [
    "1JwMWBVLtiqtscbaRHai4pqHokhFCbtoB4",
    "c4c1b72491ede1eedaca00618407ee0b772cad0d",
    {
      "addrType": "pubkey",
	@@ -297,7 +297,7 @@
    }
  ],
  [
    "3QCzvfL4ZRvmJFiWWBVwxfdaNBT8EtxB5y",
    "f6fe69bcb548a829cce4c57bf6fff8af3a5981f9",
    {
      "addrType": "script",
	@@ -315,7 +315,7 @@
    }
  ],
  [
    "2NEWDzHWwY5ZZp8CQWbB7ouNMLqCia6YRda",
    "e930e1834a4d234702773951d627cce82fbb5d2e",
    {
      "addrType": "script",
	@@ -324,7 +324,7 @@
    }
  ],
  [
    "5KQmDryMNDcisTzRp3zEq9e4awRmJrEVU1j5vFRTKpRNYPqYrMg",
    "d1fab7ab7385ad26872237f1eb9789aa25cc986bacc695e07ac571d6cdac8bc0",
    {
      "isCompressed": false,
	@@ -333,7 +333,7 @@
    }
  ],
  [
    "L39Fy7AC2Hhj95gh3Yb2AU5YHh1mQSAHgpNixvm27poizcJyLtUi",
    "b0bbede33ef254e8376aceb1510253fc3550efd0fcf84dcd0c9998b288f166b3",
    {
      "isCompressed": true,
	@@ -360,7 +360,7 @@
    }
  ],
  [
    "19dcawoKcZdQz365WpXWMhX6QCUpR9SY4r",
    "5eadaf9bb7121f0f192561a5a62f5e5f54210292",
    {
      "addrType": "pubkey",
	@@ -369,7 +369,7 @@
    }
  ],
  [
    "37Sp6Rv3y4kVd1nQ1JV5pfqXccHNyZm1x3",
    "3f210e7277c899c3a155cc1c90f4106cbddeec6e",
    {
      "addrType": "script",
	@@ -387,7 +387,7 @@
    }
  ],
  [
    "2N7FuwuUuoTBrDFdrAZ9KxBmtqMLxce9i1C",
    "99b31df7c9068d1481b596578ddbb4d3bd90baeb",
    {
      "addrType": "script",
	@@ -396,7 +396,7 @@
    }
  ],
  [
    "5KL6zEaMtPRXZKo1bbMq7JDjjo1bJuQcsgL33je3oY8uSJCR5b4",
    "c7666842503db6dc6ea061f092cfb9c388448629a6fe868d068c42a488b478ae",
    {
      "isCompressed": false,
	@@ -405,7 +405,7 @@
    }
  ],
  [
    "KwV9KAfwbwt51veZWNscRTeZs9CKpojyu1MsPnaKTF5kz69H1UN2",
    "07f0803fc5399e773555ab1e8939907e9badacc17ca129e67a2f5f2ff84351dd",
    {
      "isCompressed": true,
	@@ -432,7 +432,7 @@
    }
  ],
  [
    "13p1ijLwsnrcuyqcTvJXkq2ASdXqcnEBLE",
    "1ed467017f043e91ed4c44b4e8dd674db211c4e6",
    {
      "addrType": "pubkey",
	@@ -441,7 +441,7 @@
    }
  ],
  [
    "3ALJH9Y951VCGcVZYAdpA3KchoP9McEj1G",
    "5ece0cadddc415b1980f001785947120acdb36fc",
    {
      "addrType": "script",

**Comment by 10gic** [comment]
> How to generate address base_58_key below ?
> 
> ```
> "5KaBW9vNtWNhc3ZEDyNCiXLPdVPHCikRxSBWwV9NrpLLa4LsXi9",
> "e75d936d56377f432f404aabb406601f892fd49da90eb6ac558a733c93b47252",
> {
>   "isCompressed": false,
> @@ -189,7 +189,7 @@
> }
> ```
> 
> ],
> [
> "L1axzbSyynNYA8mCAhzxkipKkfHtAXYF4YQnhSKcLV8YXA874fgT",
> "8248bd0375f2f75d7e274ae544fb920f51784480866b102384190b1addfbaa5c",
> {
> "isCompressed": true,
> @@ -216,7 +216,7 @@
> }
> ],
> [
> "1Gqk4Tv79P91Cc1STQtU3s1W6277M2CVWu",
> "adc1cc2081a27206fae25792f28bbc55b831549d",
> {
> "addrType": "pubkey",
> @@ -225,7 +225,7 @@
> }
> ],
> [
> "33vt8ViH5jsr115AGkW6cEmEz9MpvJSwDk",
> "188f91a931947eddd7432d6e614387e32b244709",
> {
> "addrType": "script",
> @@ -243,7 +243,7 @@
> }
> ],
> [
> "2MxgPqX1iThW3oZVk9KoFcE5M4JpiETssVN",
> "3b9b3fd7a50d4f08d1a5b0f62f644fa7115ae2f3",
> {
> "addrType": "script",
> @@ -252,7 +252,7 @@
> }
> ],
> [
> "5HtH6GdcwCJA4ggWEL1B3jzBBUB8HPiBi9SBc5h9i4Wk4PSeApR",
> "091035445ef105fa1bb125eccfb1882f3fe69592265956ade751fd095033d8d0",
> {
> "isCompressed": false,
> @@ -261,7 +261,7 @@
> }
> ],
> [
> "L2xSYmMeVo3Zek3ZTsv9xUrXVAmrWxJ8Ua4cw8pkfbQhcEFhkXT8",
> "ab2b4bcdfc91d34dee0ae2a8c6b6668dadaeb3a88b9859743156f462325187af",
> {
> "isCompressed": true,
> @@ -288,7 +288,7 @@
> }
> ],
> [
> "1JwMWBVLtiqtscbaRHai4pqHokhFCbtoB4",
> "c4c1b72491ede1eedaca00618407ee0b772cad0d",
> {
> "addrType": "pubkey",
> @@ -297,7 +297,7 @@
> }
> ],
> [
> "3QCzvfL4ZRvmJFiWWBVwxfdaNBT8EtxB5y",
> "f6fe69bcb548a829cce4c57bf6fff8af3a5981f9",
> {
> "addrType": "script",
> @@ -315,7 +315,7 @@
> }
> ],
> [
> "2NEWDzHWwY5ZZp8CQWbB7ouNMLqCia6YRda",
> "e930e1834a4d234702773951d627cce82fbb5d2e",
> {
> "addrType": "script",
> @@ -324,7 +324,7 @@
> }
> ],
> [
> "5KQmDryMNDcisTzRp3zEq9e4awRmJrEVU1j5vFRTKpRNYPqYrMg",
> "d1fab7ab7385ad26872237f1eb9789aa25cc986bacc695e07ac571d6cdac8bc0",
> {
> "isCompressed": false,
> @@ -333,7 +333,7 @@
> }
> ],
> [
> "L39Fy7AC2Hhj95gh3Yb2AU5YHh1mQSAHgpNixvm27poizcJyLtUi",
> "b0bbede33ef254e8376aceb1510253fc3550efd0fcf84dcd0c9998b288f166b3",
> {
> "isCompressed": true,
> @@ -360,7 +360,7 @@
> }
> ],
> [
> "19dcawoKcZdQz365WpXWMhX6QCUpR9SY4r",
> "5eadaf9bb7121f0f192561a5a62f5e5f54210292",
> {
> "addrType": "pubkey",
> @@ -369,7 +369,7 @@
> }
> ],
> [
> "37Sp6Rv3y4kVd1nQ1JV5pfqXccHNyZm1x3",
> "3f210e7277c899c3a155cc1c90f4106cbddeec6e",
> {
> "addrType": "script",
> @@ -387,7 +387,7 @@
> }
> ],
> [
> "2N7FuwuUuoTBrDFdrAZ9KxBmtqMLxce9i1C",
> "99b31df7c9068d1481b596578ddbb4d3bd90baeb",
> {
> "addrType": "script",
> @@ -396,7 +396,7 @@
> }
> ],
> [
> "5KL6zEaMtPRXZKo1bbMq7JDjjo1bJuQcsgL33je3oY8uSJCR5b4",
> "c7666842503db6dc6ea061f092cfb9c388448629a6fe868d068c42a488b478ae",
> {
> "isCompressed": false,
> @@ -405,7 +405,7 @@
> }
> ],
> [
> "KwV9KAfwbwt51veZWNscRTeZs9CKpojyu1MsPnaKTF5kz69H1UN2",
> "07f0803fc5399e773555ab1e8939907e9badacc17ca129e67a2f5f2ff84351dd",
> {
> "isCompressed": true,
> @@ -432,7 +432,7 @@
> }
> ],
> [
> "13p1ijLwsnrcuyqcTvJXkq2ASdXqcnEBLE",
> "1ed467017f043e91ed4c44b4e8dd674db211c4e6",
> {
> "addrType": "pubkey",
> @@ -441,7 +441,7 @@
> }
> ],
> [
> "3ALJH9Y951VCGcVZYAdpA3KchoP9McEj1G",
> "5ece0cadddc415b1980f001785947120acdb36fc",
> {
> "addrType": "script",

Sorry, I don't understand your question.

**Comment by widecoin-project** [comment]
I have some question. i go through lib test address doc of BTC. i saw base_58_key.
It is applicable to generate from your tool.
Example like:

"5KaBW9vNtWNhc3ZEDyNCiXLPdVPHCikRxSBWwV9NrpLLa4LsXi9",
  "isCompressed": false,
  
"L1axzbSyynNYA8mCAhzxkipKkfHtAXYF4YQnhSKcLV8YXA874fgT",
"isCompressed": true,

"1Gqk4Tv79P91Cc1STQtU3s1W6277M2CVWu",
"addrType": "pubkey",

"1Gqk4Tv79P91Cc1STQtU3s1W6277M2CVWu",
"addrType": "pubkey",

"5HtH6GdcwCJA4ggWEL1B3jzBBUB8HPiBi9SBc5h9i4Wk4PSeApR",
"isCompressed": false,

Refer to https://github.com/bitpay/bitcore-lib/blob/master/test/data/bitcoind/base58_keys_invalid.json

Please confirm

**Comment by widecoin-project** [comment]
can give example all address in  to https://github.com/bitpay/bitcore-lib/blob/master/test/data/bitcoind/base58_keys_invalid.json ?
how to generate it and replace in base58_keys_invalid.json ?

**Pull request closed without merging**
